#!/usr/bin/env node
/* eslint-disable no-console */
const { execSync } = require('child_process');
const { writeFileSync } = require('fs');
const { resolve } = require('path');
const BranchName = require('branch-name');
const tmp = require('tmp');

if (!process.argv[2]) {
  console.error('You must provide a path to publish');
}

const GitIgnore = `
node_modules
`;

async function runPublish() {
  const branchName = await BranchName.get();
  try {
    process.chdir(process.argv[2]);
    const { name: path } = tmp.dirSync();
    execSync(`mv ${resolve(process.cwd(), 'dist')}/* ${path}`);

    execSync('git checkout gh-pages');
    execSync('git rm "*" -rf');
    writeFileSync(resolve(process.cwd(), '.gitignore'), GitIgnore);
    execSync(`mv ${path}/* ${resolve(process.cwd())}`);
    execSync('git add .');
    execSync('git commit -m "Automated publish"');
    try {
      execSync('git push origin gh-pages');
    } catch (e) {
      console.error(e);
    }
  } catch (e) {
    console.error(e);
  } finally {
    execSync(`git checkout ${branchName}`);
  }
}

runPublish().catch(console.error);
